print("Welcome to the tip calculator.")
bill=float(input("What was the total bill? $"))
tip=int(input("What percent tip would you like to give? 10, 12, or 15? "))
split=int(input("How many people to split the bill? "))
pay=round(((bill+(bill*tip/100))/split),2)
pay="{:.2f}".format(pay)
print(f"Each person should pay: ${pay}")